on: 
  push:
    branches:
    - master
    paths:
    - 'hw2.Rmd'  
name: Check Repo
jobs:
  allowed-files:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check
      run:  Rscript -e "rmarkdown::render('hw2.Rmd')"
  knit:
    runs-on: ubuntu-latest
    container:
      image: rocker/r-ver:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check
      run: Rscript -e "source('https://raw.githubusercontent.com/statprog-s1-2019/hw2/master/hw2_whitelist.R')"
      
      
